### ISSUE TITLE
Para la instalacion de node usar nvm para administrar distintas versiones de node

### ISSUE THREAD

**Issue by lgaticaq** [juanbrujo/Talus#1]
https://github.com/creationix/nvm#install-script

**Comment by juanbrujo** [comment]
dices, reemplazar la instalacion de node via brew y usar la de nvm?

**Comment by lgaticaq** [comment]
en realidad no es necesario quitar la instalación de node (binario), si no mas bien agregar la instalación de nvm

**Comment by juanbrujo** [comment]
listo agregado con brew. gracias @lgaticaq
